"""
Django settings for LMS_Project project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cood-2aik$83%a#!!7!ig#9rtq3-s!7ap9g$nr)-mx6#q=tut#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Your app's logger - keep INFO and above
        'Student_Flow_App.StudentRoadMap': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'Student_Flow_App.roadmaptesting': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django default logger - keep WARNING and above to reduce noise
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        # Azure SDK logger - suppress info/debug logs by raising level to WARNING or ERROR
        'azure.core.pipeline.policies.http_logging_policy': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Root logger fallback
        '': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework', 
    'djongo',
    'Student_Flow_App',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
from urllib.parse import quote_plus
uname = 'lmsuser'
pwd = 'EuUpskil@25'
escaped_username = quote_plus(uname)
escaped_password = quote_plus(pwd)
uri = f"mongodb+srv://{escaped_username}:{escaped_password}@lmsmongo.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
DATABASES = {
    'mongodb': {
        'ENGINE': 'djongo',

        # 'NAME': 'LMSmongodb',
        # 'CLIENT': {
        #     'host': 'mongodb+srv://kecoview:FVy5fqqCtQy3KIt6@cluster0.b9wmlid.mongodb.net/',
        #     'username': 'kecoview',
        #     'password': 'FVy5fqqCtQy3KIt6',
        #     'authMechanism': 'SCRAM-SHA-1',
        # }
        'NAME': 'eumodb',
        'ENFORCE_SCHEMA': False,  
        'CLIENT': {
            'host': uri,
            'username': uname,
            'password': pwd,
            'authMechanism': 'SCRAM-SHA-256',
        }
    },
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'eussdb',
        # 'NAME': 'staging',
        'USER': 'euserblr', 
        'PASSWORD': '6han4Sy5#', 
        'HOST': 'slnsgdhutmtbs.database.windows.net', 
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trustServerCertificate': 'yes',  # Add this to avoid SSL errors
        },
    }
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://staging-exskilence.azurewebsites.net',
    'https://live-exskilence.azurewebsites.net',
 
]

CSRF_TRUSTED_ORIGINS=[ 
    'http://localhost:3000',
     'https://staging-exskilence.azurewebsites.net',
     'https://live-exskilence.azurewebsites.net',
    ]

ROOT_URLCONF = 'LMS_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LMS_Project.wsgi.application'

AZURE_ACCOUNT_NAME = 'eustoreholder'
AZURE_ACCOUNT_KEY = 'C2+T9kL7MgZbmODARQYK/HjWSxZy2o1+IqQifEhqPAxhs/ul4pPPisrWFN50yXSBWUHy5ShSPV1B+ASthIYLYw=='
AZURE_CONTAINER = 'lmsdata'

MIGRATION_MODULES = {
    'LMS_Mongodb_App': None,
    'LMS_MSSQLdb_App': None
}
MSSQL_SERVER_NAME = 'slnkshmtbsil.database.windows.net'
MSSQL_DATABASE_NAME = 'exe_test'
MSSQL_USERNAME = 'tpssa'
MSSQL_PWD = 'TPSuser@sa123'
MSSQL_DRIVER =  'ODBC Driver 17 for SQL Server'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
