# Generated by Django 4.1.13 on 2025-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('Error_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=25)),
                ('Occurred_time', models.DateTimeField()),
                ('URL_and_Body', models.TextField()),
                ('Error_msg', models.TextField()),
                ('Stack_trace', models.TextField()),
                ('User_agent', models.TextField()),
                ('Operating_sys', models.TextField()),
            ],
        ),
    ]
