# Generated by Django 4.1.13 on 2025-05-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0002_errorlogs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='errorlogs',
            table='ErrorLogs',
        ),
    ]
