# Generated by Django 4.1.13 on 2025-05-23 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0002_errorlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogs',
            name='Occurred_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 16, 47, 14, 371357, tzinfo=datetime.timezone.utc)),
        ),
    ]
