# Generated by Django 4.1.13 on 2025-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0004_alter_sub_topics_sub_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_info',
            name='student_catogory',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MOON', 'MOON'), ('STAR', 'STAR')], default='--', max_length=20),
        ),
    ]
